language: ruby
rvm:
  - 2.1.5
before_install:
  - curl -LO https://github.com/vim/vim/archive/v8.0.1529.tar.gz
  - tar zxf v8.0.1529.tar.gz
  - cd vim-8.0.1529
  - ./configure --with-features=huge
  - make
  - sudo make install
  - cd -
script: rake ci
